# Generated by Django 4.1.13 on 2024-02-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.CharField(max_length=30)),
                ("subject", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.IntegerField()),
            ],
        ),
    ]
