# Generated by Django 4.1.13 on 2024-02-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="image",
            field=models.ImageField(default=None, upload_to="teachers/"),
            preserve_default=False,
        ),
    ]
